/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kl_erase_EraseFS */

#ifndef _Included_org_kl_erase_EraseFS
#define _Included_org_kl_erase_EraseFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseFile__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseFile
 * Signature: (Ljava/lang/String;Lorg/kl/state/OverwrideMode;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseFile__Ljava_lang_String_2Lorg_kl_state_OverwrideMode_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseFiles
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseFiles___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseFiles
 * Signature: (Lorg/kl/state/OverwrideMode;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseFiles__Lorg_kl_state_OverwrideMode_2_3Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseDirectory
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseDirectory__Ljava_lang_String_2Z
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_kl_erase_EraseFS
 * Method:    eraseDirectory
 * Signature: (Ljava/lang/String;Lorg/kl/state/OverwrideMode;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kl_erase_EraseFS_eraseDirectory__Ljava_lang_String_2Lorg_kl_state_OverwrideMode_2Z
  (JNIEnv *, jclass, jstring, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
